### ISSUE TITLE
SCSS variables names issue

### ISSUE THREAD

**Issue by snaumov** [ismay/stylelint-no-unsupported-browser-features#49] opened 2017-12-15 11:12 UTC
Hi, 

thanks for a cool plugin!

Is it suppose to correctly parse SCSS variables? I'm having a problem that if I have SCSS variables with names like 

```
$filter-background
$resize-something
```

,so contains resize/filter, the plugin throws an error regarding css-filter, and css-resize options being not supported by IE>10.

Here is my stylelint congif:

```
{
  "plugins": [
    "stylelint-no-unsupported-browser-features"
  ],
  "rules": {
    "plugin/no-unsupported-browser-features": [true, {
      "browsers": ["IE >= 10"]
    }]
  }
}
```

and exceprt of SCSS file:

```
$modal-form-filter: #3d81c4;
$resize-background: #f5f6f7;
$resize-button-border: #d8dce1;
```
and output:

```
 6:1  ⚠  Unexpected browser feature "css-filters" is not supported by IE 10,11   plugin/no-unsupported-browser-features
 7:1  ⚠  Unexpected browser feature "css-resize" is not supported by IE 10,11    plugin/no-unsupported-browser-features
```
Here is a repo with minimal config: https://github.com/snaumov/stylelint-no-browser-features-issue

**Comment by mike3run** [comment] 2017-12-16 20:40
@snaumov by default stylelint doesn't do scss you need a config for that like config-recommended-scss or something

**Comment by ismay** [comment] 2017-12-17 09:16
> @snaumov by default stylelint doesn't do scss you need a config for that like config-recommended-scss or something

Apparently stylelint 8 infers syntax automatically for `.scss`, `.less` and `.sss` (see [this medium article](https://medium.com/@bjankord/how-to-lint-scss-with-stylelint-dc87809a9878) and [the official docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-lint-scss-less-or-other-non-standard-syntax)) so running this plugin should work out of the box.

I think this is a duplicate of https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/45. It seems doiuse is somehow interpreting variables (and functions) as declarations, which is why this plugin reports the incorrect warnings. Same thing happens with regular css variables and sass functions.

Closing as duplicate of #45, we can discuss the problem there.

**Closed by ismay** 2017-12-17 09:16 UTC
