### ISSUE TITLE
Error during npm installation: `husky install` Exit status 1

### ISSUE THREAD

**Issue by ilyub** [ismay/stylelint-no-unsupported-browser-features#152] opened 2021-05-22 15:05 UTC
1001 error stylelint-no-unsupported-browser-features@5.0.0 postinstall: `husky install`
1001 error Exit status 1
1002 error Failed at the stylelint-no-unsupported-browser-features@5.0.0 postinstall script.
1002 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ismay** [comment] 2021-05-22 15:10
Thanks for reporting this @ilyub, I'll close this as a duplicate of #151, I'll take a look at this there.

**Closed by ismay** 2021-05-22 15:10 UTC
